# Publish to Sonatype Nexus
name: Release to Maven Central

on:
  workflow_dispatch:

jobs:
  checks:
    uses: ./.github/workflows/ci.yml
  build:
    needs: checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Publish to Sonatype Nexus
      run: |
        ./gradlew build \
        -P'buildkit.release'=true \
        -P'buildkit.sign'=true \
        -P'buildkit.publishing.staging-profile'=${{ secrets.SONATYPE_PROFILE }} \
        -P'buildkit.publishing.token.user'=${{ secrets.SONATYPE_TOKEN_USER }} \
        -P'buildkit.publishing.token.secret'=${{ secrets.SONATYPE_TOKEN_SECRET }}
